### ISSUE TITLE
testing LostMatchPage

### ISSUE THREAD

**Issue by BeaCoden** [coding-bootcamps-eu/2023-04-final-project-lost-and-found#130]
- Fall: bei mehreren Matches - wann wird die email adresse des users abgefangen
- Richtige wäre: bei dem click auf das gewählte(gewünschte) Match (Listeneintrag) ?
- prüfen ob dieser fall vorliegt (wäre dann falsch) nach dem alle matches als listeneintrag ausgegeben wurden ?

**Comment by yueksek-onur** [comment]
Issue erledigt!
