### ISSUE TITLE
Default Page/ Vorlage

### ISSUE THREAD

**Issue by christinemariametz** [coding-bootcamps-eu/2023-04-final-project-lost-and-found#9]
Header
Main
Footer
H1
H2
H3
Button
Inputfeld (Text/ Email)
Auswahlfeld
Liste bauen (ul,li)

**Comment by BeaCoden** [comment]
Please check the current code status of the default component in the Repo. :)
Further to-dos for me in this project can be found listed below.

ToDos for Bea:
[] add a Impressum Area
[] About Us & Impressum to Footer
[] styling (see MockUp)
[] HelloWorld Component & File rename Default.vue & DefaultView.vue
[] Links & Picture in AboutView.vue

**Comment by christinemariametz** [comment]
Passt, wie besprochen!
